In [1]:
import cv2
import numpy as np

In [72]:
#載入圖片
img = cv2.imread('3.jpg')
print(img.shape)
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(480, 640, 3)


In [74]:
# 灰階處理（？
image_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
cv2.imshow("gray", image_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [75]:
#高斯模糊
blur = cv2.blur(image_gray,(5,5))
cv2.imshow("blur", blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
low_threshold = 1
high_threshold = 90
edges = cv2.Canny(blur, low_threshold, high_threshold)
cv2.imshow("edges", edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [80]:
#ROI，直接用座標 BAD
b  = np.array([[[300, 225], [0, 480], [640, 480], [350, 225]]], dtype = np.int32)
im = np.zeros(blur.shape[:2], dtype = "uint8")
cv2.polylines(im, b, 1, 255)
cv2.fillPoly(im, b, 255)

mask = im
#cv2.imshow("masked",mask)
masked = cv2.bitwise_and(edges, edges, mask = mask)
cv2.imshow("masked", masked)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [81]:
lines = cv2.HoughLinesP(masked, 0.8, np.pi / 180, 10, lines = None, minLineLength = 100, maxLineGap = 100)
print(lines)
for line in lines:
    x1, y1, x2, y2 = line[0]
    lines1 = lines[:,0,:]
    cv2.line(img , (x1, y1), (x2, y2), (255, 0, 0), 2)
    print((x2 - x1) / (y2 -y1))
cv2.imshow("edges", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[209 321 470 330]]

 [[208 315 460 324]]

 [[231 295 437 303]]

 [[109 413 304 238]]

 [[208 320 464 325]]

 [[223 290 384 262]]

 [[241 301 423 307]]

 [[ 79 424 302 230]]

 [[232 300 443 307]]

 [[292 369 297 232]]

 [[ 78 422 301 228]]

 [[250 281 417 293]]

 [[288 238 399 274]]

 [[226 294 377 286]]

 [[225 293 397 269]]

 [[278 299 437 305]]

 [[288 350 290 234]]

 [[240 299 442 306]]

 [[ 78 423 299 231]]

 [[216 318 371 316]]

 [[295 247 396 268]]

 [[245 272 375 279]]

 [[249 280 378 262]]

 [[286 290 435 300]]

 [[241 302 356 292]]

 [[284 323 399 270]]

 [[114 410 319 226]]

 [[230 293 392 264]]

 [[243 274 423 289]]

 [[216 392 350 262]]

 [[216 319 457 319]]

 [[245 273 377 284]]

 [[417 305 518 393]]

 [[233 295 417 292]]

 [[248 278 419 290]]

 [[231 284 438 302]]

 [[100 411 290 273]]

 [[224 317 337 302]]

 [[242 274 434 301]]

 [[293 337 322 227]]

 [[276 320 378 266]]

 [[240 311 370 288]]

 [[255 277 390 263]]

 [[212 380 328 231]]

 [[223 321 438 325]]

 [[ 95 424

C:\Users\SkyEyes\miniconda3\envs\new\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in int_scalars
  import sys
