In [2]:
import cv2
import numpy as np
import imutils
import joblib
import matplotlib.pyplot as plt

In [5]:
#載入圖片
img = cv2.imread('126.jpg')
print(img.shape)
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(480, 640, 3)


In [6]:
# 灰階處理（？
image_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
cv2.imshow("gray", image_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
#高斯模糊
blur = cv2.GaussianBlur(image_gray,(5,5),0)
cv2.imshow("blur", blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
low_threshold = 1
high_threshold = 90
edges = cv2.Canny(blur, low_threshold, high_threshold)
cv2.imshow("edges", edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
#ROI，直接用座標 BAD
b  = np.array([[[0,280],  [0,450], [650,450],[640,280]]], dtype = np.int32)
im = np.zeros(blur.shape[:2], dtype = "uint8")
cv2.polylines(im, b, 1, 255)
cv2.fillPoly(im, b, 255)

mask = im
#plt.imshow(mask)
masked = cv2.bitwise_and(edges, edges, mask = mask)
cv2.imshow("masked", masked)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
lines = cv2.HoughLinesP(masked, 0.8, np.pi / 180, 10, lines = None, minLineLength = 100, maxLineGap = 100)
print(lines)
for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(img , (x1, y1), (x2, y2), (255, 0, 0), 2)
cv2.imshow("edges", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 91 420 240 286]]

 [[461 291 637 405]]

 [[ 52 431 158 348]]

 [[468 289 639 391]]

 [[ 62 435 247 290]]

 [[ 63 435 175 350]]

 [[464 292 638 405]]

 [[ 51 433 236 289]]

 [[478 294 636 389]]

 [[ 61 435 249 288]]

 [[ 83 426 230 294]]

 [[462 289 585 366]]

 [[460 291 590 373]]

 [[ 51 432 164 344]]

 [[ 85 419 249 286]]

 [[466 289 637 391]]

 [[102 411 247 285]]]
